### ISSUE TITLE
Datahub: datasources should provide consistent data 

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#363]
**Describe the bug**

Since datahub is a gateway providing API to access data from other datasources, the responsibility for providing consistent data should belongs to these datasources. 
Make sure datasources that configure in datahub can provide consistent data.

**Comment by mamafun** [comment]
Since the current behavior of a Prometheus HA setup,
(https://github.com/coreos/prometheus-operator/blob/master/Documentation/high-availability.md)
same query to different prometheus replica may have slightly different results.
According to Prometheus HA document, we may suggest users of Alameda to configure the Prometheus service with ```sessionAffinity: clusterIP``` to work around this issue. In the roadmap of Prometheus, this data inconsistency will be taken care.

**Comment by mamafun** [comment]
@rax845163 
Alameda-ai engine now handled this inconsistency.
Closing this issue. Thank you.
