### ISSUE TITLE
Was not able to follow the minishift deployment instructions

### ISSUE THREAD

**Issue by 4n4nd** [containers-ai/alameda#438]
I was trying to follow the example for deploying on minishift [(here).](https://github.com/containers-ai/alameda/tree/master/example/deployment/openshift#apply-yaml-for-kubernetes-config) 
When I try to build the image for the operator, I run into the following errors:
```
Step 4/11 : RUN ["/bin/bash", "-c", "CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags \"-X main.VERSION=`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD``git diff --quiet || echo '-dirty'` -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`'\" -a -o ./operator/manager github.com/containers-ai/alameda/operator/cmd/manager"]
 ---> Running in 0e3b15cfa673
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
can't load package: package github.com/containers-ai/alameda/operator/cmd/manager: cannot find package "github.com/containers-ai/alameda/operator/cmd/manager" in any of:
	/usr/local/go/src/github.com/containers-ai/alameda/operator/cmd/manager (from $GOROOT)
	/go/src/github.com/containers-ai/alameda/operator/cmd/manager (from $GOPATH)
```
Also in the following section: 
```
cd ../grafana
docker build -t dashboard .
```
I couldn't figure out which `../grafana` directory to cd to.
Is this supposed to be different repo?

**Comment by 4n4nd** [comment]
For the operator image, the following worked for me:
```
git clone https://github.com/containers-ai/alameda.git
cd alameda
docker build . -t operator -f operator/Dockerfile
```

**Comment by mamafun** [comment]
hi @4n4nd 
Thanks for trying this project! And sorry that the minishift document is outdated and need a major update. 

And yes, the Alameda dashboard is basically grafana. Since we do not alter any of the source code, we removed it from this repository. We only provides three customize dashboards [here](https://github.com/containers-ai/alameda/tree/master/helm/grafana/dashboards).  
> Please note that except the dashboards, you will need to setup the datasources of InfluxDB and Prometheus for Grafana as well. 

> Please also note that Alameda can still works without this dashboard

Anyway, for trying out Alameda in your minishift environment, so far the easiest way should be using the FederatorAI Operator. Please see the [quickstart guide](https://github.com/containers-ai/federatorai-operator/blob/master/docs/quickstart.md). In short, you need 3 steps to get Alameda running:
1. deploy FederatorAI Operator by K8s Manifests or via OLM 
2. apply an AlamedaService CR ([ref](https://github.com/containers-ai/federatorai-operator/blob/master/docs/crd_alamedaservice.md)).  It will pull every needed images for you.
> note: This will not install Prometheus for you. you need to provide the connection settings in AlamedaService CR.
3. apply an AlamedaScaler ([ref](https://github.com/containers-ai/alameda/blob/master/design/crd_alamedascaler.md)) to monitor your target pods.

(you may also reference my attached [alamedascaler.yaml.txt](https://github.com/containers-ai/alameda/files/3131037/alamedascaler.yaml.txt) and [alamedaservice.yaml.txt](https://github.com/containers-ai/alameda/files/3131038/alamedaservice.yaml.txt))

You can access the deployed "alameda-grafana" service to visualize Alameda results with the pre-installed dashboards. (default access is account "admin" with password "admin")

**Comment by 4n4nd** [comment]
I will try it out. Thanks for your help!
