### ISSUE TITLE
Alameda-executor log need to save in pv

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#557]
**Describe the bug**
Alameda-executor log need to save in pv.

**Environment:**
federatorai-operator: 0.2.15
alameda version: 0.3.31

**Comment by mike-liao** [comment]
The bug is because executor and recommender  not supported log file in previous image. 

Executor is supported log file in commit https://github.com/prophetstor-ai/federatorai-execution/commit/10bb23ac6370233a259ce5b1c9a686985eb0003a
Recommender is supported log file in commit  https://github.com/prophetstor-ai/federatorai-recommendation/commit/ba6c3c3bfa2dcce708ae7d11cf8c0830f85fad71
